os: linux
language: python
matrix:
  include:
  - python: 3.6
    env: TOX_ENV=py36
  - python: 3.7
    env: TOX_ENV=py37
  - python: pypy3
    env: TOX_ENV=pypy3
  - python: 3.8
    env: TOX_ENV=py38
  - python: 3.6
    env: TOX_ENV=flake8
install:
- sudo apt-get -qq update
- sudo apt-get install -y git cmake graphviz libaio-dev libavahi-client-dev libavahi-common-dev
  libusb-1.0-0-dev libxml2-dev rpm tar bzip2 gzip flex bison git
- git clone -b 'v0.18' --single-branch --depth 1 https://github.com/analogdevicesinc/libiio.git
- cd libiio
- cmake .
- make
- sudo make install
- cd ..
- pip install tox
- pip install coveralls
script:
- tox -e $TOX_ENV
after_success:
- coveralls
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
deploy:
  provider: pypi
  username: __token__
  password:
    secure: LNN0+5N7Vr0QIL6szfyEh7wfZXMWqSu8AbT8ofzjPqAzP+dfvoQrS8eGX1P9UCsRbeO5rHum4kba9N/sbpOMPTQ2f/AhIYeQ4Fi5guVLILzwmR1f0VK8RSLfblTFw+zpef6jDKaF354D7py3DFAQ00Zhxa13Z12Dli9+FmsPVx8eJB1e+9Ldh64GgPpfkz5G9wR+y1WRgPjcEoeRQuFpDa/DXqDeMytZSga+fbBWkI6jZNAuAVl/E+opoPCLeYRybmd5VUKbS04hEkjUA1P2l9hiF882PvNolXYNl2x/+D7r3qgFWCqLVZFcTleFwdlWZcx2LO46zgKrlEIIkOCocjCD/9RMe7P8RninMc212hSZMzQy5pZzTGg4aTNE+69+pqJvLIQ9RxdV3FzWmaCrm9WBMo6tcbP4W6dl75SJQOvhIhwUJIzVzzyQ8UDhGM0l5vrG98wON7pukKqFn3/S9p9vJCe7S3qk3xbc7BQs929UdRQ0MONEhAKGqZ1f4rr4pn36Cxb1F7ZK6Q3dNHxEGrcsW0sUzeAY3Za0+czJL3wd8u8D8IRKEIgy+0/NzrgkbndIsNAEwYBKakTGEdm255mv0Pls2A+rpHTQQxjj2xSiSki69uIwAkPQwXNsOf4d6xZWeE5p5O6ykvTSabQgoM2w/0Btw61ksMWD1nJ1PCA=
