os: linux
language: python

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - python: pypy3
      env: TOX_ENV=pypy3
    - python: 3.8
      env: TOX_ENV=py38
    - python: 3.6
      env: TOX_ENV=flake8

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y git cmake graphviz libaio-dev libavahi-client-dev libavahi-common-dev
    libusb-1.0-0-dev libxml2-dev rpm tar bzip2 gzip flex bison git
  - git clone -b 'v0.18' --single-branch --depth 1 https://github.com/analogdevicesinc/libiio.git
  - cd libiio
  - cmake .
  - make
  - sudo make install
  - cd ..
  - pip install tox

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
