site_name: pytest-libiio
site_description: A pytest plugin to manage interfacing with libiio contexts
site_author: Travis F. Collins

#theme: readthedocs
theme:
  name: material

repo_url: https://github.com/tfcollins/pytest-libiio

pages:
- Home: index.md

nav:
    - Home: index.md
    - Fixtures: fixtures.md
    - Emulation: emulation.md
    - CLI: cli.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
